#import "../../components.typ": *


= Conclusões <seção:considerações>

#note_from_advisor[
  Retome o objetivo do trabalho e responda diretamente às perguntas levantadas na Introdução. Sintetize o que funcionou melhor, em quais condições e com quais limitações. Não introduza novos resultados. Inclua uma discussão breve sobre ameaças à validade: interna (protocolo/implementação), externa (generalização), de construto (adequação das métricas) e de conclusão (força da evidência). Termine com possíveis próximos passos.
]

#note_from_advisor(note: todo_note)[
  Apresente as conclusões, ameaças à validade e possibilidades de continuação.
]

Este trabalho teve como objetivo avaliar métodos de aprendizado de máquina para a #glossarium.gls("classificação_multiclasse") de fluxos de rede, comparando modelos supervisionados tradicionais, estratégias de comitê e abordagens baseadas em modelos de linguagem.
Os experimentos mostraram que os classificadores baseados em árvores apresentaram desempenho elevado nos dois conjuntos de dados avaliados. Na #glossarium.gls("genis"), #glossarium.gls("random_forest") e #glossarium.gls("xgboost") atingiram desempenho praticamente perfeito, enquanto na #glossarium.gls("rosids") os modelos apresentaram diferenças mais evidentes entre as classes e maior quantidade de erros. Dessa forma, a dificuldade de classificação mostrou-se dependente das características do conjunto de dados e do cenário representado.

A avaliação dos comitês indicou que a combinação dos modelos individuais não produz necessariamente ganhos substanciais. Na #glossarium.gls("genis"), a baixa diversidade entre os classificadores limitou o benefício da combinação, uma vez que os modelos já apresentavam previsões praticamente idênticas. Na #glossarium.gls("rosids"), a maior complementaridade entre os erros permitiu ao #get_term("hard_voting") obter uma pequena melhoria sobre os classificadores individuais. Os resultados, portanto, são compatíveis com a hipótese de que a utilidade de um comitê depende não apenas da qualidade dos modelos componentes, mas também da existência de erros suficientemente distintos entre eles.

Na comparação com o modelo de linguagem, o regime #get_term("few_shot") apresentou melhora em relação ao #get_term("zero_shot"), demonstrando que exemplos fornecidos no contexto podem modificar significativamente o padrão de classificação. Entretanto, as abordagens avaliadas com #glossarium.gls("llm") permaneceram abaixo dos classificadores tradicionais em desempenho e apresentaram custo computacional substancialmente maior. Considerando que um sistema automatizado de detecção de intrusões pode precisar processar grandes quantidades de fluxos continuamente, a eficiência de inferência constitui uma restrição prática importante. Sob o protocolo utilizado, os modelos tradicionais apresentaram, portanto, uma combinação mais favorável entre desempenho preditivo e custo computacional.

Os resultados também evidenciam limitações que devem ser consideradas na interpretação das conclusões. Quanto à validade interna, os resultados dependem das decisões de pré-processamento, da seleção dos hiperparâmetros, das sementes utilizadas e do protocolo de particionamento empregado. Em particular, o desempenho praticamente perfeito observado na #glossarium.gls("genis") exige cautela, pois a base foi construída em um ambiente experimental controlado e pode apresentar padrões específicos dos cenários de coleta. Embora tenham sido removidas as colunas identificadas como metadados ou informações potencialmente relacionadas ao experimento, não se pode descartar completamente a possibilidade de informação residual dessa natureza entre as características utilizadas. Uma investigação específica sobre duplicidades, dependência entre observações e possíveis características associadas ao cenário de coleta seria necessária para avaliar essa possibilidade de forma mais rigorosa.

Quanto à validade externa, os experimentos consideraram apenas duas bases e cenários específicos, de modo que os resultados não podem ser generalizados diretamente para outras redes, tipos de tráfego ou condições operacionais. A validade de construto também apresenta limitações: métricas como #get_term("macro_f1") fornecem uma medida importante do desempenho de classificação, mas não representam sozinhas todos os requisitos de um sistema de detecção de intrusões, nos quais aspectos como falsos positivos, tempo de resposta e custo operacional também podem ser relevantes. Por fim, quanto à validade das conclusões, a quantidade de modelos, bases e configurações avaliadas limita a força das evidências para afirmações gerais sobre comitês ou modelos de linguagem. Os resultados sustentam conclusões sobre o protocolo experimental adotado, mas não permitem estabelecer que o mesmo comportamento ocorrerá em outros ambientes.

Como continuidade, trabalhos futuros podem ampliar a avaliação para outros conjuntos de dados e diferentes condições de particionamento, incluindo divisões orientadas por experimento ou por período de coleta, de modo a avaliar melhor a capacidade de generalização. Também podem ser investigadas estratégias adicionais de comitê, diferentes formas de seleção dos exemplos #get_term("few_shot") e abordagens baseadas em embeddings combinadas com classificadores tradicionais. Por fim, uma avaliação mais ampla de recursos computacionais, incluindo memória e consumo energético, pode complementar a análise de eficiência para cenários de implantação de sistemas de detecção automatizados.
