#import "../../components.typ": *


= Introdução <seção:introdução>

#note_from_advisor(note: done_note)[
  A Introdução deve responder, preferencialmente sem subseções, às seguintes perguntas: Qual é o problema? Por que ele é relevante? Qual tarefa de aprendizado de máquina será estudada? Qual é o objetivo do trabalho? Como o estudo foi conduzido, em linhas gerais? Qual é a contribuição prática ou experimental do trabalho? Termine a seção apresentando de forma clara o objetivo e, se conveniente, uma pequena lista das contribuições/atividades realizadas. Evite transformar a Introdução em uma revisão bibliográfica extensa.
]

#note_from_advisor(note: done_note)[
  Contextualize o problema e sua relevância. Defina a tarefa de aprendizado de máquina e apresente o objetivo do estudo. Explique brevemente a estratégia experimental adotada e indique o que será comparado.
]

A crescente dependência de redes de computadores para a operação de serviços e sistemas digitais torna a identificação de atividades maliciosas um componente importante da segurança da informação. Nesse contexto, sistemas de detecção de intrusões (#glossarium.gls-short("nids")) buscam identificar comportamentos que possam representar ataques ou violações da segurança da rede. Uma das possibilidades para automatizar essa tarefa consiste em utilizar técnicas de #glossarium.gls("machine_learning") sobre características extraídas do tráfego de rede, permitindo que os padrões associados a diferentes comportamentos sejam aprendidos a partir de dados históricos @buczak:2016:ml_for_cyber_security. Entre as diferentes formas de representação do tráfego, os registros de fluxo permitem caracterizar comunicações por propriedades como protocolo, portas, duração, quantidade de pacotes e volume de dados, sem a necessidade de analisar diretamente o conteúdo de cada pacote @umer:2017:flow_based_detection.

Quando os dados de rede possuem rótulos conhecidos, a detecção pode ser formulada como um problema de #glossarium.gls("aprendizado_supervisionado"). Neste trabalho, considera-se especificamente uma tarefa de #glossarium.gls("classificação_multiclasse"), na qual cada fluxo deve ser associado a uma única categoria entre as definidas pelo conjunto de dados. Essa formulação permite distinguir não apenas tráfego benigno de tráfego malicioso, mas também diferentes tipos de comportamento ou ataques. A tarefa, entretanto, pode apresentar dificuldades decorrentes da distribuição desigual das classes, da semelhança entre determinados padrões de tráfego e das características específicas do ambiente no qual os dados foram coletados.

Além da escolha do algoritmo de classificação, a combinação de diferentes modelos constitui uma estratégia para explorar possíveis diferenças nas decisões dos classificadores. Comitês podem produzir previsões por meio de votação ou pela combinação ponderada das saídas dos modelos, buscando aproveitar complementaridades entre seus erros. Mais recentemente, modelos de linguagem de grande porte também passaram a oferecer uma alternativa para tarefas de classificação por meio da descrição textual dos dados, possibilitando abordagens #get_term("zero_shot") e #get_term("few_shot"). A comparação dessas estratégias com modelos supervisionados tradicionais permite analisar não apenas a qualidade das previsões, mas também as diferenças de comportamento e de custo computacional.

Este trabalho tem como objetivo avaliar métodos de aprendizado de máquina para a classificação multiclasse de fluxos de rede e investigar como diferentes estratégias de combinação e o uso de modelos de linguagem se comportam nesse problema. Para isso, foram utilizados dois conjuntos de dados de contextos distintos, #glossarium.gls("genis") e #glossarium.gls("rosids"), que representam, respectivamente, tráfego de uma rede corporativa e de um sistema robótico baseado em #glossarium.gls("ros"). Sobre essas bases, foram comparados três modelos de referência baseados em árvores de decisão: #glossarium.gls("decision_tree"), #glossarium.gls("random_forest") e #glossarium.gls("xgboost"). A partir desses modelos, foram avaliadas diferentes estratégias de comitê, incluindo votações simples e ponderadas, além de abordagens com um modelo de linguagem executado nos regimes #get_term("zero_shot") e #get_term("few_shot").

O estudo foi conduzido a partir das versões processadas das bases, com remoção das colunas identificadas como metadados ou como informações não destinadas à previsão, seguida da seleção e transformação das características necessárias aos experimentos. Os modelos clássicos foram avaliados por meio de três #get_term("seed", plural: true), com seleção de configurações utilizando exclusivamente dados de treinamento e validação e avaliação final sobre conjuntos de teste mantidos separados. As estratégias de comitê foram construídas a partir dos três modelos de referência, e as abordagens com o modelo de linguagem foram avaliadas sobre amostras estratificadas dos conjuntos de teste. O desempenho foi analisado por meio de métricas de classificação, matrizes de confusão e medidas de diversidade e correlação dos erros, complementadas pela medição dos tempos de treinamento e inferência. Dessa forma, a comparação considera simultaneamente qualidade preditiva, comportamento por classe, complementaridade entre modelos e eficiência computacional.

A contribuição experimental do trabalho está, portanto, na análise conjunta dessas diferentes estratégias sob um mesmo protocolo de classificação e em dois contextos de tráfego de rede. Busca-se verificar em que condições a combinação de modelos oferece benefícios em relação aos classificadores individuais, como o desempenho de uma abordagem baseada em modelo de linguagem se compara aos métodos supervisionados e qual é o impacto do custo computacional dessas alternativas. Em particular, a análise da eficiência é relevante para sistemas automatizados de detecção, que podem precisar processar grandes quantidades de fluxos continuamente e, portanto, não dependem apenas da capacidade de classificação, mas também da capacidade de realizar inferência de forma eficiente.

Assim, o trabalho realiza as seguintes atividades principais:
avaliação de #glossarium.gls("decision_tree"), #glossarium.gls("random_forest") e #glossarium.gls("xgboost") em duas bases de dados de detecção de intrusões;
avaliação de diferentes estratégias de comitê e análise de sua relação com a diversidade dos erros dos modelos componentes;
comparação dos classificadores tradicionais com abordagens #get_term("zero_shot") e #get_term("few_shot") baseadas em modelo de linguagem;
análise conjunta do desempenho preditivo, dos padrões de erro e do custo computacional das abordagens avaliadas.
