"""GENIS dataset schema."""

from enum import StrEnum

from schema.common import (
    DatasetSchema,
    FeatureDataType,
    FeatureRole,
    FeatureSemanticType,
    FeatureSpec,
)


class GenisCategoryLabel(StrEnum):
    """Multiclass traffic categories defined by the GENIS dataset."""

    BENIGN = "benign"
    BRUTEFORCE = "bruteforce"
    DOS = "dos"
    RECON = "recon"


class GenisSubcategoryLabel(StrEnum):
    """Fine-grained traffic categories defined by the GENIS dataset."""

    BENIGN_ADMIN = "benign-admin"
    BENIGN_BACKGROUND = "benign-background"
    BENIGN_USER = "benign-user"

    BRUTEFORCE_FTP = "bruteforce-ftp"
    BRUTEFORCE_SMB = "bruteforce-smb"
    BRUTEFORCE_SSH = "bruteforce-ssh"

    DOS_HULK = "dos-hulk"
    DOS_ICMP = "dos-icmp"
    DOS_PUSHACK = "dos-pushack"
    DOS_SLOWLORIS = "dos-slowloris"
    DOS_UDP = "dos-udp"

    RECON_DNS = "recon-dns"
    RECON_NMAP = "recon-nmap"


GENIS_FEATURES: tuple[FeatureSpec, ...] = (
    FeatureSpec(
        label="dport",
        name="Destination Port",
        source_column_name="Dport",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination transport-layer port number.",
    ),
    FeatureSpec(
        label="syn_ack",
        name="SYN-ACK Time",
        source_column_name="SynAck",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Time between a TCP SYN packet and the corresponding SYN-ACK.",
    ),
    FeatureSpec(
        label="sequence_number",
        name="Sequence Number",
        source_column_name="Seq",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.METADATA,
        description="Network-flow sequence number that can identify packet ordering.",
    ),
    FeatureSpec(
        label="maximum_packet_size",
        name="Maximum Packet Size",
        source_column_name="Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum observed packet size in the flow.",
    ),
    FeatureSpec(
        label="source_hops",
        name="Source Hops",
        source_column_name="sHops",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of network hops associated with the source side.",
    ),
    FeatureSpec(
        label="tcp_rtt",
        name="TCP Round-Trip Time",
        source_column_name="TcpRtt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP round-trip time estimated for the flow.",
    ),
    FeatureSpec(
        label="destination_inter_packet_time_minimum",
        name="Minimum Destination Inter-Packet Time",
        source_column_name="DIntPktMin",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum inter-packet interval observed on the destination side.",
    ),
    FeatureSpec(
        label="mean_packet_size",
        name="Mean Packet Size",
        source_column_name="Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet size observed in the flow.",
    ),
    FeatureSpec(
        label="destination_packets",
        name="Destination Packets",
        source_column_name="DstPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets sent from the destination side.",
    ),
    FeatureSpec(
        label="destination_tcp_base",
        name="Destination TCP Base Sequence",
        source_column_name="DstTCPBase",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Initial TCP sequence value associated with the destination side.",
    ),
    FeatureSpec(
        label="source_ttl",
        name="Source TTL",
        source_column_name="sTtl",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="IP time-to-live value observed on the source side.",
    ),
    FeatureSpec(
        label="sport",
        name="Source Port",
        source_column_name="Sport",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source transport-layer port number.",
    ),
    FeatureSpec(
        label="total_bytes",
        name="Total Bytes",
        source_column_name="TotBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of bytes transferred by the flow.",
    ),
    FeatureSpec(
        label="destination_inter_packet_time_active",
        name="Destination Active Inter-Packet Time",
        source_column_name="DIntPktAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Active destination-side inter-packet timing statistic.",
    ),
    FeatureSpec(
        label="destination_loss",
        name="Destination Packet Loss",
        source_column_name="DstLoss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets lost on the destination side.",
    ),
    FeatureSpec(
        label="source_window_size",
        name="Source TCP Window",
        source_column_name="SrcWin",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP window size observed on the source side.",
    ),
    FeatureSpec(
        label="source_application_bytes",
        name="Source Application Bytes",
        source_column_name="SAppBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Application-level bytes transmitted by the source.",
    ),
    FeatureSpec(
        label="rate",
        name="Flow Rate",
        source_column_name="Rate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Overall traffic rate of the flow.",
    ),
    FeatureSpec(
        label="destination_bytes",
        name="Destination Bytes",
        source_column_name="DstBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of bytes transmitted by the destination side.",
    ),
    FeatureSpec(
        label="source_packets",
        name="Source Packets",
        source_column_name="SrcPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets transmitted by the source side.",
    ),
    FeatureSpec(
        label="minimum_packet_size",
        name="Minimum Packet Size",
        source_column_name="Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum observed packet size in the flow.",
    ),
    FeatureSpec(
        label="destination_rate",
        name="Destination Rate",
        source_column_name="DstRate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Traffic rate measured on the destination side.",
    ),
    FeatureSpec(
        label="ack_data_time",
        name="ACK-to-Data Time",
        source_column_name="AckDat",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Time between TCP acknowledgment and data transmission.",
    ),
    FeatureSpec(
        label="source_maximum_packet_size",
        name="Source Maximum Packet Size",
        source_column_name="sMaxPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet size observed on the source side.",
    ),
    FeatureSpec(
        label="source_inter_packet_time_maximum",
        name="Maximum Source Inter-Packet Time",
        source_column_name="SIntPktMax",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum source-side inter-packet interval.",
    ),
    FeatureSpec(
        label="loss",
        name="Packet Loss",
        source_column_name="Loss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of lost packets in the flow.",
    ),
    FeatureSpec(
        label="destination_inter_packet_time",
        name="Destination Inter-Packet Time",
        source_column_name="DIntPkt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination-side inter-packet timing statistic.",
    ),
    FeatureSpec(
        label="source_load",
        name="Source Load",
        source_column_name="SrcLoad",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Traffic load measured on the source side.",
    ),
    FeatureSpec(
        label="source_rate",
        name="Source Rate",
        source_column_name="SrcRate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Traffic rate measured on the source side.",
    ),
    FeatureSpec(
        label="destination_inter_packet_time_maximum",
        name="Maximum Destination Inter-Packet Time",
        source_column_name="DIntPktMax",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum destination-side inter-packet interval.",
    ),
    FeatureSpec(
        label="source_bytes",
        name="Source Bytes",
        source_column_name="SrcBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of bytes transmitted by the source side.",
    ),
    FeatureSpec(
        label="total_application_bytes",
        name="Total Application Bytes",
        source_column_name="TotAppByte",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total application-level bytes transmitted by the flow.",
    ),
    FeatureSpec(
        label="source_minimum_packet_size",
        name="Source Minimum Packet Size",
        source_column_name="sMinPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet size observed on the source side.",
    ),
    FeatureSpec(
        label="sum_packet_sizes",
        name="Sum of Packet Sizes",
        source_column_name="Sum",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Sum of observed packet sizes in the flow.",
    ),
    FeatureSpec(
        label="source_inter_packet_time_minimum",
        name="Minimum Source Inter-Packet Time",
        source_column_name="SIntPktMin",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum source-side inter-packet interval.",
    ),
    FeatureSpec(
        label="source_tos",
        name="Source Type of Service",
        source_column_name="sTos",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="IP type-of-service value observed on the source side.",
    ),
    FeatureSpec(
        label="destination_mean_packet_size",
        name="Destination Mean Packet Size",
        source_column_name="dMeanPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet size observed on the destination side.",
    ),
    FeatureSpec(
        label="total_packets",
        name="Total Packets",
        source_column_name="TotPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of packets in the flow.",
    ),
    FeatureSpec(
        label="source_inter_packet_time",
        name="Source Inter-Packet Time",
        source_column_name="SIntPkt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source-side inter-packet timing statistic.",
    ),
    FeatureSpec(
        label="destination_application_bytes",
        name="Destination Application Bytes",
        source_column_name="DAppBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Application-level bytes transmitted by the destination.",
    ),
    FeatureSpec(
        label="source_inter_packet_time_active",
        name="Source Active Inter-Packet Time",
        source_column_name="SIntPktAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Active source-side inter-packet timing statistic.",
    ),
    FeatureSpec(
        label="packet_count_ratio",
        name="Packet Count Ratio",
        source_column_name="PCRatio",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Ratio derived from packet counts in the flow.",
    ),
    FeatureSpec(
        label="destination_window_size",
        name="Destination TCP Window",
        source_column_name="DstWin",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP window size observed on the destination side.",
    ),
    FeatureSpec(
        label="destination_minimum_packet_size",
        name="Destination Minimum Packet Size",
        source_column_name="dMinPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet size observed on the destination side.",
    ),
    FeatureSpec(
        label="source_jitter_active",
        name="Source Active Jitter",
        source_column_name="SrcJitAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Active source-side packet timing jitter.",
    ),
    FeatureSpec(
        label="offset",
        name="Record Offset",
        source_column_name="Offset",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.IDENTIFIER,
        description="Offset associated with the record in the source data.",
    ),
    FeatureSpec(
        label="destination_maximum_packet_size",
        name="Destination Maximum Packet Size",
        source_column_name="dMaxPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet size observed on the destination side.",
    ),
    FeatureSpec(
        label="source_mean_packet_size",
        name="Source Mean Packet Size",
        source_column_name="sMeanPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet size observed on the source side.",
    ),
    FeatureSpec(
        label="destination_jitter",
        name="Destination Jitter",
        source_column_name="DstJitter",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Packet timing jitter measured on the destination side.",
    ),
    FeatureSpec(
        label="packet_loss_percentage",
        name="Packet Loss Percentage",
        source_column_name="pLoss",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Percentage or proportion of packet loss in the flow.",
    ),
    FeatureSpec(
        label="source_jitter",
        name="Source Jitter",
        source_column_name="SrcJitter",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Packet timing jitter measured on the source side.",
    ),
    FeatureSpec(
        label="duration",
        name="Flow Duration",
        source_column_name="Dur",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Duration of the network flow.",
    ),
    FeatureSpec(
        label="load",
        name="Flow Load",
        source_column_name="Load",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Overall traffic load of the flow.",
    ),
    FeatureSpec(
        label="source_address_identifier",
        name="Source Address Identifier",
        source_column_name="Ssaddr",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.IDENTIFIER,
        description="Integer identifier representing the source address.",
    ),
    FeatureSpec(
        label="run_time",
        name="Flow Runtime",
        source_column_name="RunTime",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Runtime statistic associated with the flow.",
    ),
    FeatureSpec(
        label="destination_address_identifier",
        name="Destination Address Identifier",
        source_column_name="Sdaddr",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.IDENTIFIER,
        description="Integer identifier representing the destination address.",
    ),
    FeatureSpec(
        label="destination_jitter_active",
        name="Destination Active Jitter",
        source_column_name="DstJitAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Active destination-side packet timing jitter.",
    ),
    FeatureSpec(
        label="source_inter_packet_time_idle",
        name="Source Idle Inter-Packet Time",
        source_column_name="SIntPktIdl",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Idle source-side inter-packet timing statistic.",
    ),
    FeatureSpec(
        label="source_loss",
        name="Source Packet Loss",
        source_column_name="SrcLoss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets lost on the source side.",
    ),
    FeatureSpec(
        label="destination_load",
        name="Destination Load",
        source_column_name="DstLoad",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Traffic load measured on the destination side.",
    ),
    FeatureSpec(
        label="source_tcp_base",
        name="Source TCP Base Sequence",
        source_column_name="SrcTCPBase",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Initial TCP sequence value associated with the source side.",
    ),
    FeatureSpec(
        label="protocol_arp",
        name="Protocol: ARP",
        source_column_name="Proto_arp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for Address Resolution Protocol traffic.",
    ),
    FeatureSpec(
        label="protocol_icmp",
        name="Protocol: ICMP",
        source_column_name="Proto_icmp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for ICMP traffic.",
    ),
    FeatureSpec(
        label="protocol_ipv6_icmp",
        name="Protocol: IPv6 ICMP",
        source_column_name="Proto_ipv6-icmp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for IPv6 ICMP traffic.",
    ),
    FeatureSpec(
        label="protocol_tcp",
        name="Protocol: TCP",
        source_column_name="Proto_tcp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for TCP traffic.",
    ),
    FeatureSpec(
        label="protocol_udp",
        name="Protocol: UDP",
        source_column_name="Proto_udp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for UDP traffic.",
    ),
    FeatureSpec(
        label="flags_e",
        name="TCP/Flow Flag: E",
        source_column_name="Flgs_e",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the lowercase E flow flag.",
    ),
    FeatureSpec(
        label="flags_e_star",
        name="TCP/Flow Flag: E*",
        source_column_name="Flgs_e *",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E* flow flag.",
    ),
    FeatureSpec(
        label="flags_e_d",
        name="TCP/Flow Flag: E-D",
        source_column_name="Flgs_e d",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-D flow flag.",
    ),
    FeatureSpec(
        label="flags_e_g",
        name="TCP/Flow Flag: E-G",
        source_column_name="Flgs_e g",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-G flow flag.",
    ),
    FeatureSpec(
        label="flags_e_r",
        name="TCP/Flow Flag: E-R",
        source_column_name="Flgs_e r",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-R flow flag.",
    ),
    FeatureSpec(
        label="flags_e_s",
        name="TCP/Flow Flag: E-S",
        source_column_name="Flgs_e s",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-S flow flag.",
    ),
    FeatureSpec(
        label="flags_e_u",
        name="TCP/Flow Flag: E-U",
        source_column_name="Flgs_eU",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-U flow flag.",
    ),
    FeatureSpec(
        label="state_clo",
        name="Connection State: CLO",
        source_column_name="State_CLO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the CLO connection state.",
    ),
    FeatureSpec(
        label="state_con",
        name="Connection State: CON",
        source_column_name="State_CON",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the CON connection state.",
    ),
    FeatureSpec(
        label="state_eco",
        name="Connection State: ECO",
        source_column_name="State_ECO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the ECO connection state.",
    ),
    FeatureSpec(
        label="state_fin",
        name="Connection State: FIN",
        source_column_name="State_FIN",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the FIN connection state.",
    ),
    FeatureSpec(
        label="state_int",
        name="Connection State: INT",
        source_column_name="State_INT",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the INT connection state.",
    ),
    FeatureSpec(
        label="state_nrs",
        name="Connection State: NRS",
        source_column_name="State_NRS",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the NRS connection state.",
    ),
    FeatureSpec(
        label="state_req",
        name="Connection State: REQ",
        source_column_name="State_REQ",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the REQ connection state.",
    ),
    FeatureSpec(
        label="state_rst",
        name="Connection State: RST",
        source_column_name="State_RST",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the RST connection state.",
    ),
    FeatureSpec(
        label="state_tst",
        name="Connection State: TST",
        source_column_name="State_TST",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the TST connection state.",
    ),
    FeatureSpec(
        label="state_urh",
        name="Connection State: URH",
        source_column_name="State_URH",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the URH connection state.",
    ),
    FeatureSpec(
        label="state_urhpro",
        name="Connection State: URHPRO",
        source_column_name="State_URHPRO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the URHPRO connection state.",
    ),
    FeatureSpec(
        label="binary_label",
        name="Binary Label",
        source_column_name="BinaryLabel",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.METADATA,
        description="Binary traffic label where 0 represents benign traffic and 1 represents malicious traffic.",
    ),
    FeatureSpec(
        label="category_label",
        name="Category Label",
        source_column_name="CategoryLabel",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.TARGET,
        description="Multiclass traffic category used as the primary classification target.",
        category_enum=GenisCategoryLabel,
    ),
    FeatureSpec(
        label="subcategory_label",
        name="Subcategory Label",
        source_column_name="SubCategoryLabel",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.METADATA,
        description="Fine-grained traffic subcategory retained for secondary analysis.",
        category_enum=GenisSubcategoryLabel,
    ),
)

GENIS_SCHEMA = DatasetSchema(
    dataset_name="GENIS",
    target_feature_label="category_label",
    features=GENIS_FEATURES,
)
