"""ROSIDS23 dataset schema."""

from enum import StrEnum

from .common import (
    DatasetSchema,
    FeatureDataType,
    FeatureRole,
    FeatureSemanticType,
    FeatureSpec,
)


class RosidsLabel(StrEnum):
    """Known multiclass labels in the ROSIDS23 dataset."""

    BENIGN = "Benign"
    DOS = "DoS"
    SUBFLOOD = "Subflood"
    UNAUTHORIZED_PUBLISH = "UnauthPub"
    UNAUTHORIZED_SUBSCRIBE = "UnauthSub"


ROSIDS_FEATURES: tuple[FeatureSpec, ...] = (
    FeatureSpec(
        label="flow_id",
        name="Flow ID",
        source_column_name="Flow ID",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.IDENTIFIER,
        description="Unique identifier assigned to the network flow.",
    ),
    FeatureSpec(
        label="source_ip",
        name="Source IP Address",
        source_column_name="Src IP",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.IDENTIFIER,
        description="IP address of the source endpoint.",
    ),
    FeatureSpec(
        label="source_port",
        name="Source Port",
        source_column_name="Src Port",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Transport-layer source port number.",
    ),
    FeatureSpec(
        label="destination_ip",
        name="Destination IP Address",
        source_column_name="Dst IP",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.IDENTIFIER,
        description="IP address of the destination endpoint.",
    ),
    FeatureSpec(
        label="destination_port",
        name="Destination Port",
        source_column_name="Dst Port",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Transport-layer destination port number.",
    ),
    FeatureSpec(
        label="protocol",
        name="Protocol",
        source_column_name="Protocol",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.PREDICTOR,
        description="Network transport or communication protocol.",
    ),
    FeatureSpec(
        label="timestamp",
        name="Timestamp",
        source_column_name="Timestamp",
        data_type=FeatureDataType.DATETIME,
        semantic_type=FeatureSemanticType.DATETIME,
        role=FeatureRole.METADATA,
        description="Timestamp associated with the network flow.",
    ),
    FeatureSpec(
        label="flow_duration",
        name="Flow Duration",
        source_column_name="Flow Duration",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Duration of the network flow.",
    ),
    FeatureSpec(
        label="total_forward_packets",
        name="Total Forward Packets",
        source_column_name="Tot Fwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of packets transmitted in the forward direction.",
    ),
    FeatureSpec(
        label="total_backward_packets",
        name="Total Backward Packets",
        source_column_name="Tot Bwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of packets transmitted in the backward direction.",
    ),
    FeatureSpec(
        label="total_forward_packet_length",
        name="Total Forward Packet Length",
        source_column_name="TotLen Fwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total length of packets transmitted in the forward direction.",
    ),
    FeatureSpec(
        label="total_backward_packet_length",
        name="Total Backward Packet Length",
        source_column_name="TotLen Bwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total length of packets transmitted in the backward direction.",
    ),
    FeatureSpec(
        label="forward_packet_length_maximum",
        name="Maximum Forward Packet Length",
        source_column_name="Fwd Pkt Len Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet length in the forward direction.",
    ),
    FeatureSpec(
        label="forward_packet_length_minimum",
        name="Minimum Forward Packet Length",
        source_column_name="Fwd Pkt Len Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet length in the forward direction.",
    ),
    FeatureSpec(
        label="forward_packet_length_mean",
        name="Mean Forward Packet Length",
        source_column_name="Fwd Pkt Len Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet length in the forward direction.",
    ),
    FeatureSpec(
        label="forward_packet_length_standard_deviation",
        name="Forward Packet Length Standard Deviation",
        source_column_name="Fwd Pkt Len Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of packet lengths in the forward direction.",
    ),
    FeatureSpec(
        label="backward_packet_length_maximum",
        name="Maximum Backward Packet Length",
        source_column_name="Bwd Pkt Len Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet length in the backward direction.",
    ),
    FeatureSpec(
        label="backward_packet_length_minimum",
        name="Minimum Backward Packet Length",
        source_column_name="Bwd Pkt Len Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet length in the backward direction.",
    ),
    FeatureSpec(
        label="backward_packet_length_mean",
        name="Mean Backward Packet Length",
        source_column_name="Bwd Pkt Len Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet length in the backward direction.",
    ),
    FeatureSpec(
        label="backward_packet_length_standard_deviation",
        name="Backward Packet Length Standard Deviation",
        source_column_name="Bwd Pkt Len Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of packet lengths in the backward direction.",
    ),
    FeatureSpec(
        label="flow_bytes_per_second",
        name="Flow Bytes per Second",
        source_column_name="Flow Byts/s",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average number of bytes transmitted per second by the flow.",
    ),
    FeatureSpec(
        label="flow_packets_per_second",
        name="Flow Packets per Second",
        source_column_name="Flow Pkts/s",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average number of packets transmitted per second by the flow.",
    ),
    FeatureSpec(
        label="flow_inter_arrival_time_mean",
        name="Mean Flow Inter-Arrival Time",
        source_column_name="Flow IAT Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean inter-arrival time between packets in the flow.",
    ),
    FeatureSpec(
        label="flow_inter_arrival_time_standard_deviation",
        name="Flow Inter-Arrival Time Standard Deviation",
        source_column_name="Flow IAT Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of flow packet inter-arrival times.",
    ),
    FeatureSpec(
        label="flow_inter_arrival_time_maximum",
        name="Maximum Flow Inter-Arrival Time",
        source_column_name="Flow IAT Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet inter-arrival time within the flow.",
    ),
    FeatureSpec(
        label="flow_inter_arrival_time_minimum",
        name="Minimum Flow Inter-Arrival Time",
        source_column_name="Flow IAT Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet inter-arrival time within the flow.",
    ),
    FeatureSpec(
        label="forward_inter_arrival_time_total",
        name="Total Forward Inter-Arrival Time",
        source_column_name="Fwd IAT Tot",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total inter-arrival time for forward-direction packets.",
    ),
    FeatureSpec(
        label="forward_inter_arrival_time_mean",
        name="Mean Forward Inter-Arrival Time",
        source_column_name="Fwd IAT Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean inter-arrival time for forward-direction packets.",
    ),
    FeatureSpec(
        label="forward_inter_arrival_time_standard_deviation",
        name="Forward Inter-Arrival Time Standard Deviation",
        source_column_name="Fwd IAT Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of forward packet inter-arrival times.",
    ),
    FeatureSpec(
        label="forward_inter_arrival_time_maximum",
        name="Maximum Forward Inter-Arrival Time",
        source_column_name="Fwd IAT Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum forward packet inter-arrival time.",
    ),
    FeatureSpec(
        label="forward_inter_arrival_time_minimum",
        name="Minimum Forward Inter-Arrival Time",
        source_column_name="Fwd IAT Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum forward packet inter-arrival time.",
    ),
    FeatureSpec(
        label="backward_inter_arrival_time_total",
        name="Total Backward Inter-Arrival Time",
        source_column_name="Bwd IAT Tot",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total inter-arrival time for backward-direction packets.",
    ),
    FeatureSpec(
        label="backward_inter_arrival_time_mean",
        name="Mean Backward Inter-Arrival Time",
        source_column_name="Bwd IAT Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean inter-arrival time for backward-direction packets.",
    ),
    FeatureSpec(
        label="backward_inter_arrival_time_standard_deviation",
        name="Backward Inter-Arrival Time Standard Deviation",
        source_column_name="Bwd IAT Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of backward packet inter-arrival times.",
    ),
    FeatureSpec(
        label="backward_inter_arrival_time_maximum",
        name="Maximum Backward Inter-Arrival Time",
        source_column_name="Bwd IAT Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum backward packet inter-arrival time.",
    ),
    FeatureSpec(
        label="backward_inter_arrival_time_minimum",
        name="Minimum Backward Inter-Arrival Time",
        source_column_name="Bwd IAT Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum backward packet inter-arrival time.",
    ),
    FeatureSpec(
        label="forward_push_flag_count",
        name="Forward PSH Flag Count",
        source_column_name="Fwd PSH Flags",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of PSH flags set on forward-direction packets.",
    ),
    FeatureSpec(
        label="backward_push_flag_count",
        name="Backward PSH Flag Count",
        source_column_name="Bwd PSH Flags",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of PSH flags set on backward-direction packets.",
    ),
    FeatureSpec(
        label="forward_urgent_flag_count",
        name="Forward URG Flag Count",
        source_column_name="Fwd URG Flags",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of URG flags set on forward-direction packets.",
    ),
    FeatureSpec(
        label="backward_urgent_flag_count",
        name="Backward URG Flag Count",
        source_column_name="Bwd URG Flags",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of URG flags set on backward-direction packets.",
    ),
    FeatureSpec(
        label="forward_header_length",
        name="Forward Header Length",
        source_column_name="Fwd Header Len",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total header length for forward-direction packets.",
    ),
    FeatureSpec(
        label="backward_header_length",
        name="Backward Header Length",
        source_column_name="Bwd Header Len",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total header length for backward-direction packets.",
    ),
    FeatureSpec(
        label="forward_packets_per_second",
        name="Forward Packets per Second",
        source_column_name="Fwd Pkts/s",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Forward-direction packet rate.",
    ),
    FeatureSpec(
        label="backward_packets_per_second",
        name="Backward Packets per Second",
        source_column_name="Bwd Pkts/s",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Backward-direction packet rate.",
    ),
    FeatureSpec(
        label="packet_length_minimum",
        name="Minimum Packet Length",
        source_column_name="Pkt Len Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet length observed in the flow.",
    ),
    FeatureSpec(
        label="packet_length_maximum",
        name="Maximum Packet Length",
        source_column_name="Pkt Len Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet length observed in the flow.",
    ),
    FeatureSpec(
        label="packet_length_mean",
        name="Mean Packet Length",
        source_column_name="Pkt Len Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet length observed in the flow.",
    ),
    FeatureSpec(
        label="packet_length_standard_deviation",
        name="Packet Length Standard Deviation",
        source_column_name="Pkt Len Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of packet lengths in the flow.",
    ),
    FeatureSpec(
        label="packet_length_variance",
        name="Packet Length Variance",
        source_column_name="Pkt Len Var",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Variance of packet lengths in the flow.",
    ),
    FeatureSpec(
        label="fin_flag_count",
        name="FIN Flag Count",
        source_column_name="FIN Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of FIN flags observed in the flow.",
    ),
    FeatureSpec(
        label="syn_flag_count",
        name="SYN Flag Count",
        source_column_name="SYN Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of SYN flags observed in the flow.",
    ),
    FeatureSpec(
        label="rst_flag_count",
        name="RST Flag Count",
        source_column_name="RST Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of RST flags observed in the flow.",
    ),
    FeatureSpec(
        label="psh_flag_count",
        name="PSH Flag Count",
        source_column_name="PSH Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of PSH flags observed in the flow.",
    ),
    FeatureSpec(
        label="ack_flag_count",
        name="ACK Flag Count",
        source_column_name="ACK Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of ACK flags observed in the flow.",
    ),
    FeatureSpec(
        label="urg_flag_count",
        name="URG Flag Count",
        source_column_name="URG Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of URG flags observed in the flow.",
    ),
    FeatureSpec(
        label="cwe_flag_count",
        name="CWE Flag Count",
        source_column_name="CWE Flag Count",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of CWE flags observed in the flow.",
    ),
    FeatureSpec(
        label="ece_flag_count",
        name="ECE Flag Count",
        source_column_name="ECE Flag Cnt",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of ECE flags observed in the flow.",
    ),
    FeatureSpec(
        label="down_up_ratio",
        name="Downstream-to-Upstream Ratio",
        source_column_name="Down/Up Ratio",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Ratio between downstream and upstream traffic.",
    ),
    FeatureSpec(
        label="packet_size_average",
        name="Average Packet Size",
        source_column_name="Pkt Size Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average size of packets observed in the flow.",
    ),
    FeatureSpec(
        label="forward_segment_size_average",
        name="Average Forward Segment Size",
        source_column_name="Fwd Seg Size Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average forward TCP segment size.",
    ),
    FeatureSpec(
        label="backward_segment_size_average",
        name="Average Backward Segment Size",
        source_column_name="Bwd Seg Size Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average backward TCP segment size.",
    ),
    FeatureSpec(
        label="forward_bytes_per_block_average",
        name="Average Forward Bytes per Block",
        source_column_name="Fwd Byts/b Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average forward bytes transmitted per block.",
    ),
    FeatureSpec(
        label="forward_packets_per_block_average",
        name="Average Forward Packets per Block",
        source_column_name="Fwd Pkts/b Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average forward packets transmitted per block.",
    ),
    FeatureSpec(
        label="forward_block_rate_average",
        name="Average Forward Block Rate",
        source_column_name="Fwd Blk Rate Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average rate of forward traffic blocks.",
    ),
    FeatureSpec(
        label="backward_bytes_per_block_average",
        name="Average Backward Bytes per Block",
        source_column_name="Bwd Byts/b Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average backward bytes transmitted per block.",
    ),
    FeatureSpec(
        label="backward_packets_per_block_average",
        name="Average Backward Packets per Block",
        source_column_name="Bwd Pkts/b Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average backward packets transmitted per block.",
    ),
    FeatureSpec(
        label="backward_block_rate_average",
        name="Average Backward Block Rate",
        source_column_name="Bwd Blk Rate Avg",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average rate of backward traffic blocks.",
    ),
    FeatureSpec(
        label="subflow_forward_packets",
        name="Subflow Forward Packets",
        source_column_name="Subflow Fwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of forward packets attributed to the subflow.",
    ),
    FeatureSpec(
        label="subflow_forward_bytes",
        name="Subflow Forward Bytes",
        source_column_name="Subflow Fwd Byts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of forward bytes attributed to the subflow.",
    ),
    FeatureSpec(
        label="subflow_backward_packets",
        name="Subflow Backward Packets",
        source_column_name="Subflow Bwd Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of backward packets attributed to the subflow.",
    ),
    FeatureSpec(
        label="subflow_backward_bytes",
        name="Subflow Backward Bytes",
        source_column_name="Subflow Bwd Byts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of backward bytes attributed to the subflow.",
    ),
    FeatureSpec(
        label="initial_forward_window_bytes",
        name="Initial Forward Window Bytes",
        source_column_name="Init Fwd Win Byts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Initial TCP window size advertised by the forward endpoint.",
    ),
    FeatureSpec(
        label="initial_backward_window_bytes",
        name="Initial Backward Window Bytes",
        source_column_name="Init Bwd Win Byts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Initial TCP window size advertised by the backward endpoint.",
    ),
    FeatureSpec(
        label="forward_active_data_packets",
        name="Forward Active Data Packets",
        source_column_name="Fwd Act Data Pkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of forward packets carrying active application data.",
    ),
    FeatureSpec(
        label="forward_segment_size_minimum",
        name="Minimum Forward Segment Size",
        source_column_name="Fwd Seg Size Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum forward TCP segment size.",
    ),
    FeatureSpec(
        label="active_mean",
        name="Mean Active Time",
        source_column_name="Active Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean duration of active periods within the flow.",
    ),
    FeatureSpec(
        label="active_standard_deviation",
        name="Active Time Standard Deviation",
        source_column_name="Active Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of active periods within the flow.",
    ),
    FeatureSpec(
        label="active_maximum",
        name="Maximum Active Time",
        source_column_name="Active Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum duration of an active period within the flow.",
    ),
    FeatureSpec(
        label="active_minimum",
        name="Minimum Active Time",
        source_column_name="Active Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum duration of an active period within the flow.",
    ),
    FeatureSpec(
        label="idle_mean",
        name="Mean Idle Time",
        source_column_name="Idle Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean duration of idle periods within the flow.",
    ),
    FeatureSpec(
        label="idle_standard_deviation",
        name="Idle Time Standard Deviation",
        source_column_name="Idle Std",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Standard deviation of idle periods within the flow.",
    ),
    FeatureSpec(
        label="idle_maximum",
        name="Maximum Idle Time",
        source_column_name="Idle Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum duration of an idle period within the flow.",
    ),
    FeatureSpec(
        label="idle_minimum",
        name="Minimum Idle Time",
        source_column_name="Idle Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum duration of an idle period within the flow.",
    ),
    FeatureSpec(
        label="label",
        name="Label",
        source_column_name="Label",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.TARGET,
        description="Multiclass ROSIDS23 traffic-security label.",
        category_enum=RosidsLabel,
    ),
)

ROSIDS_SCHEMA = DatasetSchema(
    dataset_name="ROSIDS23",
    target_feature_label="label",
    features=ROSIDS_FEATURES,
)
