"""GENIS dataset loading functions."""

from pathlib import Path

import pandas as pd

from loading.common import DatasetBundle
from loading.loader import DATA_ROOT, CsvDatasetLoader
from schema.common import (
    FeatureDataType,
    FeatureRole,
    FeatureSemanticType,
    SourceDatasetSchema,
    SourceFeatureSpec,
)
from schema.genis import GenisCategoryLabel, GenisSubcategoryLabel

SOURCE_GENIS_FEATURES: tuple[SourceFeatureSpec, ...] = (
    SourceFeatureSpec(
        label="destination_port",
        name="Destination Port",
        source_column_name="Dport",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination port number.",
    ),
    SourceFeatureSpec(
        label="syn_ack_time",
        name="SYN-ACK Time",
        source_column_name="SynAck",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP connection setup time between the SYN and SYN-ACK packets.",
    ),
    SourceFeatureSpec(
        label="sequence_number",
        name="Sequence Number",
        source_column_name="Seq",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.METADATA,
        description="Argus sequence number.",
    ),
    SourceFeatureSpec(
        label="maximum_duration",
        name="Maximum Duration",
        source_column_name="Max",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum duration among the aggregated records.",
    ),
    SourceFeatureSpec(
        label="source_hops",
        name="Source Hops",
        source_column_name="sHops",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Estimated number of IP hops from the source to this point.",
    ),
    SourceFeatureSpec(
        label="tcp_rtt",
        name="TCP Round-Trip Time",
        source_column_name="TcpRtt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP connection setup round-trip time, equal to the sum of SYN-ACK and ACK-to-data times.",
    ),
    SourceFeatureSpec(
        label="destination_interpacket_time_minimum",
        name="Minimum Destination Inter-Packet Time",
        source_column_name="DIntPktMin",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum destination inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="mean_duration",
        name="Mean Duration",
        source_column_name="Mean",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Average duration of the aggregated records.",
    ),
    SourceFeatureSpec(
        label="amount_of_destination_packets",
        name="Destination Packets",
        source_column_name="DstPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets transmitted from destination to source.",
    ),
    SourceFeatureSpec(
        label="destination_tcp_base",
        name="Destination TCP Base Sequence",
        source_column_name="DstTCPBase",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination TCP base sequence number.",
    ),
    SourceFeatureSpec(
        label="source_ttl",
        name="Source TTL",
        source_column_name="sTtl",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source-to-destination TTL value.",
    ),
    SourceFeatureSpec(
        label="source_port",
        name="Source Port",
        source_column_name="Sport",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source port number.",
    ),
    SourceFeatureSpec(
        label="total_bytes",
        name="Total Bytes",
        source_column_name="TotBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total number of transaction bytes.",
    ),
    SourceFeatureSpec(
        label="destination_interpacket_time_active",
        name="Active Destination Inter-Packet Time",
        source_column_name="DIntPktAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination active inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="amount_of_destination_package_loss",
        name="Destination Loss",
        source_column_name="DstLoss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination packets retransmitted or dropped.",
    ),
    SourceFeatureSpec(
        label="source_window_in_bytes",
        name="Source TCP Window",
        source_column_name="SrcWin",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source TCP window advertisement.",
    ),
    SourceFeatureSpec(
        label="source_application_bytes",
        name="Source Application Bytes",
        source_column_name="SAppBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Application bytes transmitted from source to destination.",
    ),
    SourceFeatureSpec(
        label="packet_rate",
        name="Packet Rate",
        source_column_name="Rate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of packets transmitted per second.",
    ),
    SourceFeatureSpec(
        label="destination_bytes",
        name="Destination Bytes",
        source_column_name="DstBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Bytes transmitted from destination to source.",
    ),
    SourceFeatureSpec(
        label="amount_of_source_packets",
        name="Source Packets",
        source_column_name="SrcPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Packets transmitted from source to destination.",
    ),
    SourceFeatureSpec(
        label="minimum_duration",
        name="Minimum Duration",
        source_column_name="Min",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum duration among the aggregated records.",
    ),
    SourceFeatureSpec(
        label="destination_packet_rate",
        name="Destination Packet Rate",
        source_column_name="DstRate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination-to-source packets transmitted per second.",
    ),
    SourceFeatureSpec(
        label="acknowledgement_data_time",
        name="ACK-to-Data Time",
        source_column_name="AckDat",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="TCP connection setup time between the SYN-ACK and ACK packets.",
    ),
    SourceFeatureSpec(
        label="source_maximum_packet_size",
        name="Maximum Source Packet Size",
        source_column_name="sMaxPktSz",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet size transmitted by the source.",
    ),
    SourceFeatureSpec(
        label="source_interpacket_time_maximum",
        name="Maximum Source Inter-Packet Time",
        source_column_name="SIntPktMax",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum source inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="amount_of_package_loss",
        name="Packet Loss",
        source_column_name="Loss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Packets retransmitted or dropped.",
    ),
    SourceFeatureSpec(
        label="destination_interpacket_time",
        name="Destination Inter-Packet Time",
        source_column_name="DIntPkt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="source_load",
        name="Source Load",
        source_column_name="SrcLoad",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source traffic load in bits per second.",
    ),
    SourceFeatureSpec(
        label="source_packet_rate",
        name="Source Packet Rate",
        source_column_name="SrcRate",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source-to-destination packets transmitted per second.",
    ),
    SourceFeatureSpec(
        label="destination_interpacket_time_maximum",
        name="Maximum Destination Inter-Packet Time",
        source_column_name="DIntPktMax",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum destination inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="source_bytes",
        name="Source Bytes",
        source_column_name="SrcBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Bytes transmitted from source to destination.",
    ),
    SourceFeatureSpec(
        label="total_application_bytes",
        name="Total Application Bytes",
        source_column_name="TotAppByte",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total application bytes.",
    ),
    SourceFeatureSpec(
        label="source_minimum_packet_size",
        name="Minimum Source Packet Size",
        source_column_name="sMinPktSz",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet size transmitted by the source.",
    ),
    SourceFeatureSpec(
        label="total_duration",
        name="Total Duration",
        source_column_name="Sum",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total accumulated duration of the aggregated records.",
    ),
    SourceFeatureSpec(
        label="source_interpacket_time_minimum",
        name="Minimum Source Inter-Packet Time",
        source_column_name="SIntPktMin",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum source inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="source_tos",
        name="Source TOS",
        source_column_name="sTos",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source TOS byte value.",
    ),
    SourceFeatureSpec(
        label="destination_mean_packet_size",
        name="Mean Destination Packet Size",
        source_column_name="dMeanPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet size transmitted by the destination.",
    ),
    SourceFeatureSpec(
        label="total_packets",
        name="Total Packets",
        source_column_name="TotPkts",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total transaction packet count.",
    ),
    SourceFeatureSpec(
        label="source_interpacket_time",
        name="Source Inter-Packet Time",
        source_column_name="SIntPkt",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="destination_application_bytes",
        name="Destination Application Bytes",
        source_column_name="DAppBytes",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Application bytes transmitted from destination to source.",
    ),
    SourceFeatureSpec(
        label="source_interpacket_time_active",
        name="Active Source Inter-Packet Time",
        source_column_name="SIntPktAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source active inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="producer_consumer_ratio",
        name="Producer-Consumer Ratio",
        source_column_name="PCRatio",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Producer-consumer traffic ratio.",
    ),
    SourceFeatureSpec(
        label="destination_window_in_bytes",
        name="Destination TCP Window",
        source_column_name="DstWin",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination TCP window advertisement.",
    ),
    SourceFeatureSpec(
        label="destination_minimum_packet_size",
        name="Minimum Destination Packet Size",
        source_column_name="dMinPktSz",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Minimum packet size transmitted by the destination.",
    ),
    SourceFeatureSpec(
        label="source_active_jitter",
        name="Source Active Jitter",
        source_column_name="SrcJitAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source active jitter in milliseconds.",
    ),
    SourceFeatureSpec(
        label="offset_in_bytes",
        name="Record offset",
        source_column_name="Offset",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.METADATA,
        description="Byte offset of the record in the file or stream.",
    ),
    SourceFeatureSpec(
        label="destination_maximum_packet_size",
        name="Maximum Destination Packet Size",
        source_column_name="dMaxPktSz",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Maximum packet size transmitted by the destination.",
    ),
    SourceFeatureSpec(
        label="source_mean_packet_size",
        name="Mean Source Packet Size",
        source_column_name="sMeanPktSz",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Mean packet size transmitted by the source.",
    ),
    SourceFeatureSpec(
        label="destination_jitter",
        name="Destination Jitter",
        source_column_name="DstJitter",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination jitter in milliseconds.",
    ),
    SourceFeatureSpec(
        label="packet_loss_percentage",
        name="Packet Loss Percentage",
        source_column_name="pLoss",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Percentage of packets retransmitted or dropped.",
    ),
    SourceFeatureSpec(
        label="source_jitter",
        name="Source Jitter",
        source_column_name="SrcJitter",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source jitter in milliseconds.",
    ),
    SourceFeatureSpec(
        label="duration",
        name="Record Duration",
        source_column_name="Dur",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total duration of the record.",
    ),
    SourceFeatureSpec(
        label="load",
        name="Load",
        source_column_name="Load",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Traffic load in bits per second.",
    ),
    SourceFeatureSpec(
        label="source_address_connection_count",
        name="Source Address Connection Count",
        source_column_name="Ssaddr",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of connections with the same service and source address.",
    ),
    SourceFeatureSpec(
        label="run_time",
        name="Active Flow Runtime",
        source_column_name="RunTime",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Total active flow runtime, equal to the sum of the aggregated record durations.",
    ),
    SourceFeatureSpec(
        label="destination_address_connection_count",
        name="Destination Address Connection Count",
        source_column_name="Sdaddr",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Number of connections with the same service and destination address.",
    ),
    SourceFeatureSpec(
        label="destination_active_jitter",
        name="Destination Active Jitter",
        source_column_name="DstJitAct",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination active jitter in milliseconds.",
    ),
    SourceFeatureSpec(
        label="source_interpacket_time_idle",
        name="Idle Source Inter-Packet Time",
        source_column_name="SIntPktIdl",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source idle inter-packet arrival time in milliseconds.",
    ),
    SourceFeatureSpec(
        label="amount_of_source_packets_loss",
        name="Source Loss",
        source_column_name="SrcLoss",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source packets retransmitted or dropped.",
    ),
    SourceFeatureSpec(
        label="destination_load",
        name="Destination Load",
        source_column_name="DstLoad",
        data_type=FeatureDataType.FLOAT,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Destination traffic load in bits per second.",
    ),
    SourceFeatureSpec(
        label="source_tcp_base",
        name="Source TCP Base Sequence",
        source_column_name="SrcTCPBase",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.NUMERIC,
        role=FeatureRole.PREDICTOR,
        description="Source TCP base sequence number.",
    ),
    SourceFeatureSpec(
        label="protocol_arp",
        name="Protocol: ARP",
        source_column_name="Proto_arp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for ARP traffic.",
    ),
    SourceFeatureSpec(
        label="protocol_icmp",
        name="Protocol: ICMP",
        source_column_name="Proto_icmp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for ICMP traffic.",
    ),
    SourceFeatureSpec(
        label="protocol_ipv6_icmp",
        name="Protocol: IPv6 ICMP",
        source_column_name="Proto_ipv6-icmp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for IPv6 ICMP traffic.",
    ),
    SourceFeatureSpec(
        label="protocol_tcp",
        name="Protocol: TCP",
        source_column_name="Proto_tcp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for TCP traffic.",
    ),
    SourceFeatureSpec(
        label="protocol_udp",
        name="Protocol: UDP",
        source_column_name="Proto_udp",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for UDP traffic.",
    ),
    SourceFeatureSpec(
        label="flags_e",
        name="Flow Flag: E",
        source_column_name="Flgs_e",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_star",
        name="Flow Flag: E*",
        source_column_name="Flgs_e *",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E* flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_d",
        name="Flow Flag: E-D",
        source_column_name="Flgs_e d",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-D flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_g",
        name="Flow Flag: E-G",
        source_column_name="Flgs_e g",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-G flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_r",
        name="Flow Flag: E-R",
        source_column_name="Flgs_e r",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-R flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_s",
        name="Flow Flag: E-S",
        source_column_name="Flgs_e s",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-S flow flag.",
    ),
    SourceFeatureSpec(
        label="flags_e_u",
        name="Flow Flag: E-U",
        source_column_name="Flgs_eU",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the E-U flow flag.",
    ),
    SourceFeatureSpec(
        label="state_clo",
        name="Transaction State: CLO",
        source_column_name="State_CLO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the CLO transaction state.",
    ),
    SourceFeatureSpec(
        label="state_con",
        name="Transaction State: CON",
        source_column_name="State_CON",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the CON transaction state.",
    ),
    SourceFeatureSpec(
        label="state_eco",
        name="Transaction State: ECO",
        source_column_name="State_ECO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the ECO transaction state.",
    ),
    SourceFeatureSpec(
        label="state_fin",
        name="Transaction State: FIN",
        source_column_name="State_FIN",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the FIN transaction state.",
    ),
    SourceFeatureSpec(
        label="state_int",
        name="Transaction State: INT",
        source_column_name="State_INT",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the INT transaction state.",
    ),
    SourceFeatureSpec(
        label="state_nrs",
        name="Transaction State: NRS",
        source_column_name="State_NRS",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the NRS transaction state.",
    ),
    SourceFeatureSpec(
        label="state_req",
        name="Transaction State: REQ",
        source_column_name="State_REQ",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the REQ transaction state.",
    ),
    SourceFeatureSpec(
        label="state_rst",
        name="Transaction State: RST",
        source_column_name="State_RST",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the RST transaction state.",
    ),
    SourceFeatureSpec(
        label="state_tst",
        name="Transaction State: TST",
        source_column_name="State_TST",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the TST transaction state.",
    ),
    SourceFeatureSpec(
        label="state_urh",
        name="Transaction State: URH",
        source_column_name="State_URH",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the URH transaction state.",
    ),
    SourceFeatureSpec(
        label="state_urhpro",
        name="Transaction State: URHPRO",
        source_column_name="State_URHPRO",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.PREDICTOR,
        description="One-hot indicator for the URHPRO transaction state.",
    ),
    SourceFeatureSpec(
        label="binary_label",
        name="Binary Label",
        source_column_name="BinaryLabel",
        data_type=FeatureDataType.INTEGER,
        semantic_type=FeatureSemanticType.BINARY,
        role=FeatureRole.METADATA,
        description="Binary traffic label: 1 for malicious traffic and 0 for benign traffic.",
    ),
    SourceFeatureSpec(
        label="category_label",
        name="Category Label",
        source_column_name="CategoryLabel",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.TARGET,
        description="High-level traffic category identifying benign traffic or the attack type.",
        category_enum=GenisCategoryLabel,
    ),
    SourceFeatureSpec(
        label="subcategory_label",
        name="Subcategory Label",
        source_column_name="SubCategoryLabel",
        data_type=FeatureDataType.STRING,
        semantic_type=FeatureSemanticType.CATEGORICAL,
        role=FeatureRole.METADATA,
        description="Specific traffic category retained for optional secondary analysis.",
        category_enum=GenisSubcategoryLabel,
    ),
)

SOURCE_GENIS_SCHEMA = SourceDatasetSchema(
    dataset_name="GENIS",
    target_feature_label="category_label",
    features=SOURCE_GENIS_FEATURES,
)


def load_genis(
    training_csv_file_path: Path,
    test_csv_file_path: Path,
) -> DatasetBundle:
    """Load the official GENIS training and test CSV files.

    Args:
        training_csv_file_path: Path to the GENIS training CSV file.
        test_csv_file_path: Path to the GENIS test CSV file.

    Returns:
        A dataset bundle containing the GENIS training and test partitions.

    Raises:
        CsvLoadingError: If either CSV file cannot be loaded or does not
            conform to the GENIS schema.
    """

    dataset_loader = CsvDatasetLoader(SOURCE_GENIS_SCHEMA)

    return dataset_loader.load_bundle(
        training_csv_file_path=training_csv_file_path,
        test_csv_file_path=test_csv_file_path,
    )


def merge_genis_partitions(
    genis_dataset_bundle: DatasetBundle,
) -> pd.DataFrame:
    """Merge the GENIS training and test DataFrames."""

    if genis_dataset_bundle.train is None:
        raise ValueError("GENIS training partition is not available.")

    if genis_dataset_bundle.test is None:
        raise ValueError("GENIS test partition is not available.")

    return pd.concat(
        (
            genis_dataset_bundle.train.data_frame,
            genis_dataset_bundle.test.data_frame,
        ),
        ignore_index=True,
    )


genis_dataset_bundle = load_genis(
    training_csv_file_path=DATA_ROOT / "genis/genis-60-sec-train.csv",
    test_csv_file_path=DATA_ROOT / "genis/genis-60-sec-test.csv",
)
source_genis_df = merge_genis_partitions(genis_dataset_bundle)
